[project]
name = "minimal-example"

[targets.dev]
dsn = "${AQUEDUCT_DEV_DSN}"
vars = { schedule = "5m" }

[targets.prod]
dsn = "${AQUEDUCT_PROD_DSN}"
vars = { schedule = "30s" }

[apply]
lock_timeout = "30s"
allow_full_refresh = true
